/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.10 helmet.gltf --transform 
Files: helmet.gltf [29.77KB] > helmet-transformed.glb [279.23KB] (-838%)
Author: HoliestMallard (https://sketchfab.com/holiestmallard)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/mjolnir-gen-2-odst-helmet-free-0c6ca4dc74e3492b9b095be16dfc19cf
Title: Mjolnir Gen 2 ODST Helmet (Free)
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export function Model(props) {
  const { nodes, materials } = useGLTF('/helmet-transformed.glb')
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.Tekka_ODST_Dorsal_crown_Color_G10_0.geometry} material={materials.PaletteMaterial001} rotation={[-Math.PI / 2, 0, 0]} scale={2.601} />
      <mesh geometry={nodes.Tekka_ODST_Dorsal_crown_Visor_0.geometry} material={materials.PaletteMaterial002} rotation={[-Math.PI / 2, 0, 0]} scale={2.601} />
    </group>
  )
}

useGLTF.preload('/helmet-transformed.glb')
